### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.0
  description: Microsoft Application Virtualization 5.0 folgt der Fixed-Lifecycle-Richtlinie.
  ms.date: 09/01/2020
  keywords: 'for Remote Desktop Services,for Terminal Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.0
summary: |+
  Microsoft Application Virtualization 5.0 folgt der [Fixed](/lifecycle/policies/fixed)-Lifecycle-Richtlinie.

  Dies gilt f√ºr die folgenden Editionen: for Remote Desktop Services, for Terminal Services, for Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 01/10/2023
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 01/10/2023
  - version: Service Pack 2
    startDate: 12/02/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>Links 
  * [Produktinformationen](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)
  * [Service Pack-Richtlinie](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>Editionen 
  * for Remote Desktop Services
  * for Terminal Services
  * for Windows Desktops